name: My First Github Action
on: [push]
jobs:
    build-app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with: 
                node-version: '14'
            - name: Install node_modules
              run: npm 
            - name: Build the project 
              run: npm run build
            - name: Sets the vercel env
              run: |
                cd build
                mkdir .vercel
                touch project.json
                echo '{"projectId":"prj_VDRaCXahzxocHsw5lvnxoervMCHO",orgId:"PfsyJaN88sVDiPJbo7ooPcxI"}' > project.json
            - name: Deploying the project
              run: npm run deploy
            - name: Setup finish
              run: echo "hurray!"


