name: My First Github Action
on: [push]
jobs:
    build-app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with: 
                node-version: '16'
            - name: Install node_modules
              run: yarn 
            - name: Build the project 
              run: yarn build
            - name: Sets the vercel env
              run: |
                cd build
                mkdir project.json
                echo {"orgId":"PfsyJaN88sVDiPJbo7ooPcxI","projectId":"prj_VDRaCXahzxocHsw5lvnxoervMCHO"}
            - name: Deploying the project
              run: yarn deploy
            - name: Setup finish      
              run: echo "hurray!"

